# This is a basic workflow to help you get started with Actions

name: ATS User docker image

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract branch name
        id: extract_branch
        run: echo "BRANCH_NAME=$GITHUB_REF_NAME" >> $GITHUB_ENV

      - name: Extract docker tag name
        id: extract_tag
        run: echo "BRANCH_TAG=$(echo ${GITHUB_REF_NAME} | sed 's/[^[:alnum:]\.\_\-]/-/g')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}      

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./docker/ATS-User-Env.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/watershed_workflow-ats:${{ env.BRANCH_TAG }}
          build-args: DOCKER_TAG=${{ env.BRANCH_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
